
version: "3.1"
services: 

  db:
    image: postgres
    container_name: app_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=spfeiras
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app_network

  app:
    container_name: app_web
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=spfeiras
      - POSTGRES_HOST=app_database
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 